In [73]:
import numpy as np

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

from torch.utils.data import Dataset
from torch.utils.data import DataLoader

In [81]:
class CustomDataset(Dataset):
    def __init__(self):
        self.x_data = torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  80], 
                               [96,  98,  100],   
                               [73,  66,  70]])
        self.y_data = torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])
    def __len__(self):
        return len(self.x_data)
    def __getitem__(self, idx):
        x = torch.FloatTensor(self.x_data[idx])
        y = torch.FloatTensor(self.y_data[idx])
        return x, y

In [82]:
x_train0  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  80], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])


In [83]:
dataset = CustomDataset()
dataloader = DataLoader(dataset, batch_size = 2, shuffle = True)

In [84]:
class multi_lin_reg_model(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1)
    
    def forward(self, x):
        return self.linear(x)

In [77]:
#model = nn.Linear(3, 1)
model = multi_lin_reg_model()
print(list(model.parameters()))

optimizer = optim.SGD(model.parameters(), lr = 1e-5)

[Parameter containing:
tensor([[ 0.3703, -0.2704,  0.2092]], requires_grad=True), Parameter containing:
tensor([-0.3228], requires_grad=True)]


In [58]:
W = torch.zeros((3, 1), requires_grad = True)
b = torch.zeros(1, requires_grad = True)

optimizer = optim.SGD([W, b], lr = 1e-5)

In [85]:
epochs = 10000

for epoch in range(epochs):
    for batch_idx, samples in enumerate(dataloader):
        x_train, y_train = samples
        hypothesis = x_train @ W + b
        prediction = model.forward(x_train)

        #loss = torch.mean((hypothesis-y_train)**2)
    
    
        loss = F.mse_loss(prediction, y_train)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if epoch%100 == 0:
            print('epoch{:4d}/{} hypothesis: {}  cost: {:.6f}'.format(
                epoch, epochs, prediction.squeeze().detach(), loss.item()
            ))


epoch   0/10000 hypothesis: tensor([29.7749, 23.5064])  cost: 19067.792969
epoch   0/10000 hypothesis: tensor([95.5924, 83.0437])  cost: 9741.111328
epoch   0/10000 hypothesis: 113.47000885009766  cost: 1484.560181
epoch 100/10000 hypothesis: tensor([200.7979, 153.8261])  cost: 13.177094
epoch 100/10000 hypothesis: tensor([175.3722, 143.8931])  cost: 12.500123
epoch 100/10000 hypothesis: 188.27432250976562  cost: 10.721188
epoch 200/10000 hypothesis: tensor([197.5741, 174.8059])  cost: 14.728398
epoch 200/10000 hypothesis: tensor([143.4541, 186.9240])  cost: 2.908108
epoch 200/10000 hypothesis: 151.6642303466797  cost: 0.112741
epoch 300/10000 hypothesis: tensor([144.2333, 153.4271])  cost: 3.512162
epoch 300/10000 hypothesis: tensor([187.1827, 176.5177])  cost: 8.445354
epoch 300/10000 hypothesis: 199.0968780517578  cost: 9.590653
epoch 400/10000 hypothesis: tensor([152.1044, 197.5816])  cost: 1.256181
epoch 400/10000 hypothesis: tensor([175.5619, 185.5438])  cost: 9.996250
epoch 400/

epoch4200/10000 hypothesis: tensor([184.7686, 179.8249])  cost: 0.042103
epoch4200/10000 hypothesis: tensor([142.5231, 196.2236])  cost: 0.161808
epoch4200/10000 hypothesis: 152.4521484375  cost: 0.204438
epoch4300/10000 hypothesis: tensor([142.2794, 195.8672])  cost: 0.047838
epoch4300/10000 hypothesis: tensor([152.2937, 184.5248])  cost: 0.156021
epoch4300/10000 hypothesis: 179.6573028564453  cost: 0.117441
epoch4400/10000 hypothesis: tensor([184.7826, 142.4674])  cost: 0.132853
epoch4400/10000 hypothesis: tensor([152.4711, 179.8204])  cost: 0.127095
epoch4400/10000 hypothesis: 196.01971435546875  cost: 0.000389
epoch4500/10000 hypothesis: tensor([142.4911, 179.8860])  cost: 0.127078
epoch4500/10000 hypothesis: tensor([184.7415, 152.4608])  cost: 0.139583
epoch4500/10000 hypothesis: 196.03265380859375  cost: 0.001066
epoch4600/10000 hypothesis: tensor([179.8862, 184.8001])  cost: 0.026455
epoch4600/10000 hypothesis: tensor([196.2058, 142.5475])  cost: 0.171039
epoch4600/10000 hypothe

epoch8400/10000 hypothesis: tensor([152.1777, 195.7295])  cost: 0.052366
epoch8400/10000 hypothesis: tensor([142.3666, 184.5627])  cost: 0.162837
epoch8400/10000 hypothesis: 179.77578735351562  cost: 0.050271
epoch8500/10000 hypothesis: tensor([195.7723, 152.2115])  cost: 0.048275
epoch8500/10000 hypothesis: tensor([184.5838, 179.7602])  cost: 0.115345
epoch8500/10000 hypothesis: 142.5057373046875  cost: 0.255770
epoch8600/10000 hypothesis: tensor([142.4984, 179.9062])  cost: 0.128584
epoch8600/10000 hypothesis: tensor([152.2926, 184.6625])  cost: 0.099751
epoch8600/10000 hypothesis: 195.9009552001953  cost: 0.009810
epoch8700/10000 hypothesis: tensor([152.3932, 196.0061])  cost: 0.077341
epoch8700/10000 hypothesis: tensor([179.8728, 142.4722])  cost: 0.119564
epoch8700/10000 hypothesis: 184.6409454345703  cost: 0.128920
epoch8800/10000 hypothesis: tensor([142.3945, 152.2362])  cost: 0.105704
epoch8800/10000 hypothesis: tensor([195.6714, 184.4738])  cost: 0.192418
epoch8800/10000 hypot

In [11]:
print(W, b)

tensor([[0.],
        [0.],
        [0.]], requires_grad=True) tensor([0.], requires_grad=True)


In [12]:
x_train@W + b

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)

In [86]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.2289, 0.6517, 0.1428]], requires_grad=True), Parameter containing:
tensor([-0.3302], requires_grad=True)]


In [89]:
x_train0 @ list(model.parameters())[0].view(3, 1) + list(model.parameters())[1]


tensor([[152.2206],
        [184.5819],
        [179.7651],
        [195.7847],
        [142.3835]], grad_fn=<AddBackward0>)