In [17]:
import numpy as np

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

In [97]:
class MyDataset(torch.utils.data.Dataset):
    """Some Information about MyDataset"""
    def __init__(self):
        super(MyDataset, self).__init__()
        self.x = torch.FloatTensor([[1, 2, 1, 1],
           [2, 1, 3, 2],
           [3, 1, 3, 4],
           [4, 1, 5, 5],
           [1, 7, 5, 5],
           [1, 2, 5, 6],
           [1, 6, 6, 6],
           [1, 7, 7, 7]])

        self.y = torch.LongTensor([2, 2, 2, 1, 1, 1, 0, 0])
        #self.y_onehot = torch.zeros(8, 3)
        #self.y_onehot.scatter_(1, self.y.unsqueeze(1), 1)

    def __getitem__(self, index):
        x = torch.FloatTensor(self.x[index])
        y = torch.tensor(self.y[index], dtype = torch.long)
        return x, y

    def __len__(self):
        return len(self.x)

In [98]:
class SoftMaxClassifierModule(nn.Module):
    """Some Information about SoftMaxClassifierModule"""
    def __init__(self):
        super(SoftMaxClassifierModule, self).__init__()
        self.linear = nn.Linear(4, 3)

    def forward(self, x):

        return self.linear(x)

In [99]:
dataset = MyDataset()
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [100]:
model = SoftMaxClassifierModule()
optimizer = torch.optim.SGD(model.parameters(), lr=1e-2)

In [101]:
epochs = 1000

for epoch in range(epochs):
    for batch_idx, xy in enumerate(dataloader):
        x_train, y_train = xy
        prediction = model(x_train)
        loss = F.cross_entropy(prediction, y_train)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if epoch % 20 == 0:
            print('epoch {:4d}/{}, batch {}, prediction {}, loss {}'.format(
                epoch, epochs, batch_idx, prediction.detach().squeeze(), loss
            ))

/tmp/ipykernel_888/3916825992.py:20: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y = torch.tensor(self.y[index], dtype = torch.long)


epoch    0/1000, batch 0, prediction tensor([[ 2.1575,  0.6679, -1.2908],
        [ 1.0823, -0.7838, -0.3176]]), loss 1.216212511062622
epoch    0/1000, batch 1, prediction tensor([[ 0.4108, -0.4138, -0.3503],
        [ 2.0113,  0.1423, -1.2989]]), loss 1.7247424125671387
epoch    0/1000, batch 2, prediction tensor([[ 1.3841,  1.4131, -0.9972],
        [ 1.8151,  1.4362, -1.4324]]), loss 0.633833646774292
epoch    0/1000, batch 3, prediction tensor([[ 0.7466, -0.0705, -0.2288],
        [ 0.4183,  0.1929, -0.2233]]), loss 1.529341220855713
epoch   20/1000, batch 0, prediction tensor([[-0.5176, -0.0667,  0.2310],
        [ 1.3724,  0.7817, -0.3541]]), loss 0.967697262763977
epoch   20/1000, batch 1, prediction tensor([[-0.6016,  0.5280,  0.5210],
        [ 0.9334,  1.1527, -0.5514]]), loss 0.875906229019165
epoch   20/1000, batch 2, prediction tensor([[ 0.2241, -0.0247,  0.1886],
        [ 1.4577,  0.9320, -0.5707]]), loss 0.7945561408996582
epoch   20/1000, batch 3, prediction tensor([[

epoch  460/1000, batch 0, prediction tensor([[ 2.9208,  1.8647, -2.9665],
        [-1.2245, -0.3820,  1.9944]]), loss 0.212651327252388
epoch  460/1000, batch 1, prediction tensor([[ 1.8149,  0.7099, -0.7249],
        [-1.7731,  0.1012,  1.3186]]), loss 0.8711825013160706
epoch  460/1000, batch 2, prediction tensor([[ 2.0037,  1.6935, -2.1626],
        [ 1.3998,  2.3303, -2.8755]]), loss 0.4476441740989685
epoch  460/1000, batch 3, prediction tensor([[-3.4668,  1.8821,  1.5656],
        [-2.9218,  1.4759,  1.8932]]), loss 0.5305480360984802
epoch  480/1000, batch 0, prediction tensor([[-3.5772,  2.0401,  1.5180],
        [-1.3160, -0.3297,  2.0336]]), loss 0.294807106256485
epoch  480/1000, batch 1, prediction tensor([[-3.0308,  1.6783,  1.7998],
        [ 1.4219,  2.5234, -3.0906]]), loss 0.4640759825706482
epoch  480/1000, batch 2, prediction tensor([[ 1.9386,  1.8649, -2.2688],
        [-1.9632,  0.2932,  1.3168]]), loss 0.4994594156742096
epoch  480/1000, batch 3, prediction tensor

epoch  920/1000, batch 0, prediction tensor([[-4.4047,  2.5845,  1.8011],
        [-2.1202, -0.3507,  2.8588]]), loss 0.2115396410226822
epoch  920/1000, batch 1, prediction tensor([[ 3.4386,  2.6973, -4.3169],
        [-2.2895,  0.3464,  1.5898]]), loss 0.32965168356895447
epoch  920/1000, batch 2, prediction tensor([[ 1.6935,  1.2392, -1.1328],
        [-4.0910,  2.0218,  2.5164]]), loss 0.7292200326919556
epoch  920/1000, batch 3, prediction tensor([[ 1.7796,  2.9022, -3.8272],
        [ 2.4170,  2.1925, -3.0747]]), loss 0.4360654652118683
epoch  940/1000, batch 0, prediction tensor([[ 1.5363,  1.3120, -1.0484],
        [-4.2162,  2.0410,  2.6225]]), loss 0.6487201452255249
epoch  940/1000, batch 1, prediction tensor([[-2.3832,  0.3140,  1.7160],
        [ 3.1867,  2.7268, -4.0945]]), loss 0.36152541637420654
epoch  940/1000, batch 2, prediction tensor([[-4.4236,  2.4331,  1.9713],
        [-2.1566, -0.3866,  2.9311]]), loss 0.265424519777298
epoch  940/1000, batch 3, prediction ten

In [74]:
print(list(model.parameters()))


[Parameter containing:
tensor([[-4.2512, -0.4969,  4.0222, -1.4844],
        [ 0.7138, -0.0418, -0.7892,  1.5441],
        [ 3.5629,  0.9892, -2.9965, -0.2744]], requires_grad=True), Parameter containing:
tensor([-3.2445, -1.3347,  4.5795], requires_grad=True)]


In [76]:
x = torch.FloatTensor([[1, 2, 1, 1],
           [2, 1, 3, 2],
           [3, 1, 3, 4],
           [4, 1, 5, 5],
           [1, 7, 5, 5],
           [1, 2, 5, 6],
           [1, 6, 6, 6],
           [1, 7, 7, 7]])

In [82]:
re = list(model.parameters())[0] @ x[1].T+ list(model.parameters())[1]


In [83]:
re.sum()

tensor(0.7817, grad_fn=<SumBackward0>)

In [102]:
result = model.forward(x_train)

In [103]:
print (result)

tensor([[ 1.7932,  3.0198, -3.9583],
        [ 1.3770,  1.5536, -1.1306]], grad_fn=<AddmmBackward0>)
